package com.mcpdbwizard.pub;

/**
 * Product branding strings, in one place.
 * <p>
 * These used to be {@code PARAM_*} placeholder tokens rewritten by {@code sed} when a release
 * was cut. That step no longer ran, so the tokens travelled into generated code verbatim — a
 * regenerated tree contained 36,837 literal {@code PARAM_PROD_NAME}s, and every generated file's
 * header read "Generated by PARAM_PROD_NAME PARAM_PRODUCT_VERSION build PARAM_BUILD". Holding the
 * values here instead means the generator concatenates a real string and there is nothing left to
 * substitute after the build.
 * <p>
 * <b>The values are real branding as of 2026-08-07</b>, filled in by the rename recorded in
 * {@code docs/rename-plan.md}. They were provisional {@code SUBST_*} placeholders until then; that
 * prefix existed to be greppable as a family and distinct from the {@code PARAM_} token each
 * replaced, so the migration could be counted rather than believed. Both families should now be
 * absent from a regenerated tree, and the rename's check script asserts exactly that.
 * <p>
 * <b>This class is the only place product branding belongs.</b> Not because duplication is untidy,
 * but because of the arithmetic: {@code param_prod_name} alone reaches ~36,837 places in a single
 * regeneration. Anything hard-coded elsewhere is invisible to that count and will be missed — which
 * is exactly what happened to the documentation links, nine of which sat in
 * {@code SAAdminWrangler} as literal URLs and went on pointing at a dead site for years. Add the
 * constant here and reference it; never retype the value.
 * <p>
 * <b>Why this lives in com.mcpdbwizard.pub and not in the generator.</b> {@link LibraryInfo}
 * reports the same product identity to generated programs at run time, and pub SHIPS WITH
 * generated code, so it must never depend on com.mcpdbwizard.app. Putting the constants the
 * other way round -- in pub, which app already imports in 30 files -- gives one source of
 * truth without inverting that dependency. A second copy inside pub would have to be kept in
 * step by hand, and would drift the first time only one side was edited.
 * <p>
 * Only values that genuinely survive into generated output live here. Tokens the
 * generator substitutes per run — {@code PARAM_AUTHOR} (the config's author name),
 * {@code PARAM_TARGET_PARAM_*}, and the script tokens {@code PARAM_JDBCJAR}/{@code PARAM_JAVAC}/…
 * — are deliberately absent: replacing those with a constant would bake one generation's data
 * into every customer's output.
 * <p>
 * {@code PARAM_COPYRIGHT_NOTICE} was listed above until 2026-08-04, on the same reasoning. It did
 * not belong there: nothing substitutes it, and it never reached generated output — its only
 * appearances were the javadoc headers of 45 hand-written sources in this package and in
 * {@code app.common}, where it stood for <b>this project's own</b> notice rather than a customer's.
 * Those now carry the real notice, so the token is gone from the tree entirely. The distinction to
 * keep is between a token the generator <i>writes into someone else's file</i> and one merely left
 * unsubstituted in ours; only the first kind must stay a token.
 *
 * @author devteam@mcpdbwizard.com
 * Copyright 2003-2026 ATB Consultancy Services Ltd
 * (formerly Orinda Software Ltd, Dublin, Ireland)
 */
public class Namer {

    /**
     * Short product name. Replaces {@code PARAM_PROD_NAME} (36,837 occurrences per regen).
     * <p>
     * <b>Spelling matters and is not free choice.</b> {@code MCPDBWizard} is the product name as it
     * appears in prose and in emitted text; {@code McpDbWizard} is the Java identifier form and
     * {@code com.mcpdbwizard} the package form. Use this constant rather than retyping it.
     */
    public static final String param_prod_name = "MCPDBWizard";

    /**
     * Long product name. Replaces {@code PARAM_PRODUCT_NAME_LONG}.
     * <p>
     * <b>Deliberately does NOT read "MCPDBWizard for Oracle", and should not be changed to.</b>
     * ORACLE is a registered trademark of Oracle America, Inc., whose third-party usage guidelines
     * permit truthful references to compatibility but not incorporating the mark into another
     * product's name. The decisive point is narrower than the trademark question, though: this
     * constant is stamped into generated PL/SQL and Java that lands in customers' databases and
     * source trees, where a later change cannot be recalled — unlike a web page. "for Oracle
     * Database" belongs in the README, the web UI and the website, all of which can be edited in an
     * afternoon.
     */
    public static final String param_product_name_long = "MCPDBWizard";

    /**
     * Alternate product-name token. Replaces {@code PARAM_PRODUCT_NAME}.
     * <p>
     * Note where this one ends up: 56 of its uses are <b>SQL comment hints</b> of the form
     * {@code select /* MCPDBWizard *&#47; …}, which is what a customer's DBA sees in {@code V$SQL}
     * when they ask who is running a dictionary query. Keep it short and keep it stable.
     */
    public static final String param_product_name = "MCPDBWizard";

    /** Product version. Replaces {@code PARAM_PRODUCT_VERSION}. */
    public static final String param_product_version = "7";

    /** Bare version token. Replaces {@code PARAM_VERSION}. */
    public static final String param_version = "7";

    /**
     * Build identifier, in Oracle's {@code YYYYMMDDHH24MI} shape — e.g. {@code 202608020937}.
     * Replaces {@code PARAM_BUILD}.
     * <p>
     * Computed ONCE per JVM, at class initialisation, so every file emitted by a single
     * generation run carries the same stamp. It therefore identifies the RUN rather than a
     * release build: two generations a minute apart produce different values. That is
     * acceptable here because the stamp only ever reaches generated <i>comments</i>, alongside
     * the header timestamp that already varies per run — which is why the project compares
     * regenerated trees with comment blocks stripped.
     * <p>
     * Java's pattern letters differ from Oracle's: {@code HH24} is Java {@code HH} (24-hour)
     * and Oracle's {@code MI} is Java {@code mm} (minutes); Java's {@code MM} is months.
     */
    public static final String param_build =
            new java.text.SimpleDateFormat("yyyyMMddHHmm").format(new java.util.Date());

    /**
     * Product web address. Replaces {@code PARAM_PRODUCT_WWW}.
     * <p>
     * <b>A BARE HOSTNAME, with no scheme.</b> Its call sites supply their own — one of them reads
     * {@code "Go to http://" + param_product_www + "/pl_sql_tab.html"} — so putting
     * {@code https://} here yields {@code http://https://mcpdbwizard.com/…}. Use
     * {@link #param_product_url} where a complete URL is wanted, and {@link #faq(String)} for
     * documentation links.
     */
    public static final String param_product_www = "mcpdbwizard.com";

    /** The product site as a complete URL. Prefer {@link #faq(String)} for documentation links. */
    public static final String param_product_url = "https://" + param_product_www;

    /**
     * Who makes it. This is the <b>current</b> vendor, and is a different question from the
     * copyright notice in these files' headers — that records a chain of title
     * ("...ATB Consultancy Services Ltd (formerly Orinda Software Ltd, Dublin, Ireland)") and must
     * not be rewritten to match a rename.
     */
    public static final String param_vendor_name = "ATB Consultancy Services Ltd";

    /** Where a user is told to send a log file when the generator fails. */
    public static final String param_support_email = "devteam@mcpdbwizard.com";

    /**
     * Documentation link emitted into generated comments as "See: ...".
     * Replaces {@code PARAM_JAVA_PARAM_LIMIT_URL}.
     */
    public static final String param_java_param_limit_url = faq("java-parameter-limit");

    /**
     * A documentation URL for {@code theTopic}, e.g. {@code faq("logging")}.
     * <p>
     * <b>Absolute on purpose, and it must stay absolute.</b> These links are emitted into
     * customers' source files, where they outlive this tool entirely: someone opening a generated
     * file years from now, on a machine that never had {@value #param_prod_name} installed, still
     * has to be able to follow them. Pointing them at a running web UI instead would be broken by
     * construction — that is an internal deployment on a port from a range, usually containerised
     * and firewalled.
     * <p>
     * The web UI serves <b>the same paths</b> from the same sources, so its own in-app warnings can
     * link to {@code /faq/<topic>} on whatever instance is running and keep working with no route
     * to the internet — which matters, because a large share of Oracle sites are air-gapped. That
     * half belongs to the web module and must not reach back into here: {@code pub} ships with
     * generated code and cannot depend on {@code app} or {@code web}, so these constants are
     * compile-time and cannot be made instance-aware.
     */
    public static String faq(String theTopic) {
        return param_product_url + "/faq/" + theTopic;
    }

    private Namer() {
        // Constants only: never instantiated. The former instance getters were unreachable for
        // exactly this reason and have been removed.
    }
}
